#!/usr/bin/env bash

# Copyright 2016 Rafal Zajac <rzajac@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is maintained at http://github.com/rzajac/vagrant-prov

###########################################################
# Provisioning configuration. All provisioning scripts
# by default include this file.
###########################################################

# The directory where all provisioning scripts are.
PROVISION_SH_DIR=/provision

###########################################################
# Project configuration
###########################################################

# The name of the project.
# It must contain only letters and digits.
PROJECT_NAME="MyProject"

# The project directory name.
# This directory will be created in /usr/local/var/www/.
# It must contain only letters and digits.
# IMPORTANT
# This has to match with the line in Vagrantfile:
# config.vm.synced_folder "project", "/usr/local/var/www/myproject", :owner => "vagrant"
PROJECT_DIR_NAME="myproject"

# The path to where index file is located. 
# Relative to project root folder.
PROJECT_INDEX_DIR=""

# The project development domain.
PROJECT_DEV_DOMAIN="project.dev"

###########################################################
# Apache.
###########################################################

# Enable Apache provisioning. Set to "no" to disable. 
APACHE_ENABLE="yes"

# Apache modules to enable.
APACHE_MODULES="rewrite"

###########################################################
# Nginx.
###########################################################

# Enable Nginx provisioning. Set to "no" to disable. 
NGINX_ENABLE="no"

###########################################################
# PHP 5.5.
###########################################################

# Enable PHP 5.5 provisioning. Set to "no" to disable.
PHP5_ENABLE="yes"

# The list of PHP packages to install.
PHP5_PACKAGES="php5-cli php5-json php5-dev php5-mysql php5-curl php5-gd"
PHP5_PACKAGES+=" php-pear php5-imagick php5-mcrypt php5-memcached"

PHP5_XDEBUG="yes"

# Pick web server to configure PHP with.
# Valid values are empty string or: apache, nginx
PHP5_WEB_SERVER="apache"

###########################################################
# PHP 7.x.
###########################################################

# Enable PHP 7.x provisioning. Set to "no" to disable.
PHP7_ENABLE="no"

# The list of PHP packages to install.
PHP7_PACKAGES="php7.0-common php7.0-cli php7.0-json php7.0-dev php7.0-mysql php7.0-curl php7.0-gd"
PHP7_PACKAGES+=" php7.0-mcrypt php7.0-mbstring"
PHP7_PACKAGES+=" php-memcached php-msgpack php-igbinary"

PHP7_XDEBUG="yes"

# Pick web server to configure PHP with.
# Valid values are empty string or: apache, nginx
PHP7_WEB_SERVER="nginx"

###########################################################
# MySQL.
###########################################################

# Enable MySQL provisioning. Set to "no" to disable. 
MYSQL_ENABLE="yes"

# The password to set for MySQL root user.
MYSQL_ROOT_PASS="r00t"

MYSQL_APP_USER="${PROJECT_NAME}User"
MYSQL_APP_PASS="${PROJECT_NAME}Pass"

MYSQL_APP_DB="${PROJECT_NAME}"

###########################################################
# Memcached.
###########################################################

# Enable memcahced provisioning. Set to "no" to disable. 
MEMCACHED_ENABLE="yes"

###########################################################
# Redis.
###########################################################

# Enable redis provisioning. Set to "yes" to enable.
REDIS_ENABLE="no"

###########################################################
# Beanstalkd.
###########################################################

# Enable beanstalkd provisioning. Set to "yes" to enable.
BEANSTALK_ENABLE="no"
